bpbridge:
  root: ${BPBRIDGE_IP}
  getRandomOfferRoute: '/getRandomOffers'
  shopIDToURLRoute: '/shopIDToUrl'
  matchAttributeRoute: '/matchAttribute'
  cleanURLRoute: '/cleanURL'
  matchAttributeWithMapRoute: '/'

shoprulesgenerator:
  root: '/'
  get-rules-route: '/'
urlcleaner:
  root: '/'
  clean-u-r-l-route: '/'

